# Generated by Django 5.2.3 on 2026-07-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='chapter',
            field=models.CharField(blank=True, max_length=100, verbose_name='章'),
        ),
    ]
