# Generated by Django 5.2.3 on 2026-07-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_studysession_reviewlog_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='trap',
            field=models.TextField(blank=True, verbose_name='解説'),
        ),
    ]
