# Generated by Django 5.2.3 on 2026-07-27 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=255, verbose_name='問題')),
                ('back', models.TextField(verbose_name='答え・判断基準')),
                ('category', models.CharField(choices=[('instant', '即答'), ('elimination', '選択肢消去'), ('formula', '数式'), ('pytorch', 'PyTorch対応')], default='instant', max_length=20, verbose_name='種類')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name='論点')),
                ('trap', models.TextField(blank=True, verbose_name='ひっかけ')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('correct_reviews', models.PositiveIntegerField(default=0)),
                ('avg_seconds', models.FloatField(default=0)),
                ('last_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='study.card')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(help_text='0=Again, 1=Hard, 2=Good, 3=Easy')),
                ('seconds', models.FloatField(default=0)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='study.card')),
            ],
        ),
    ]
