# Generated by Django 5.2.3 on 2026-07-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_card_trap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('instant', '即答'), ('elimination', '選択肢消去'), ('formula', '数式'), ('pytorch', 'PyTorch対応'), ('term', '用語')], default='instant', max_length=20, verbose_name='種類'),
        ),
    ]
