# Generated by Django 5.2.3 on 2026-07-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='category_filter',
            field=models.CharField(blank=True, max_length=20, verbose_name='絞り込んだ種類'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='chapter_filter',
            field=models.CharField(blank=True, max_length=100, verbose_name='絞り込んだ章'),
        ),
    ]
